"""
Notification types.
"""

NOTIFICATION_ASSIGNMENT = "ASSIGNMENT"

NOTIFICATION_SYNC = "SYNC"

NOTIFICATION_ANOMALY = "ANOMALY"

NOTIFICATION_LCR = "LCR"

NOTIFICATION_SYSTEM = "SYSTEM"

NOTIFICATION_TYPES = [
    NOTIFICATION_ASSIGNMENT,
    NOTIFICATION_SYNC,
    NOTIFICATION_ANOMALY,
    NOTIFICATION_LCR,
    NOTIFICATION_SYSTEM,
]